Repository codestates-seb/seb39_main_060, pull requests merged in 2022-10, with the labels that each got.

#158 [Feat] mypage 반응형 구현
  client/src/App.js
  client/src/components/PageComponent/Main/GitHubBtn/GitHubBtnBlue.js
  client/src/components/PageComponent/Main/GitHubBtn/GitHubBtnGray.js
  client/src/components/PageComponent/Main/GitHubBtn/GitHubBtnMyGray.js
  client/src/components/PageComponent/Main/GitHubGrass.js
  client/src/components/PageComponent/Main/GitHubRepo.js
  client/src/components/PageComponent/Main/MyIntro.js
  client/src/components/PageComponent/Main/MyProfile.js
  client/src/components/PageComponent/Main/MyStudyList/Carousel.js
  client/src/components/PageComponent/Main/MyStudyList/DoneList.js
  client/src/components/PageComponent/Main/MyStudyList/ProgressList.js
  client/src/components/PageComponent/Main/MyStudyList/ShortListSection.js
  client/src/pages/Main.js
Labels: frontend

#160 [Fix] 주말간 API 변경 및 버그 수정 실시
  server/src/main/java/com/team_60/Mocco/alarm/controller/AlarmController.java
  server/src/main/java/com/team_60/Mocco/alarm/service/AlarmService.java
  server/src/main/java/com/team_60/Mocco/alarm/service/AlarmServiceImpl.java
  server/src/main/java/com/team_60/Mocco/comment/controller/CommentController.java
  server/src/main/java/com/team_60/Mocco/helper/scheduler/Scheduler.java
  server/src/main/java/com/team_60/Mocco/helper/sse/SseDto.java
  server/src/main/java/com/team_60/Mocco/helper/sse/SseService.java
  server/src/main/java/com/team_60/Mocco/member/mapper/MemberMapper.java
  server/src/main/java/com/team_60/Mocco/member/service/MemberServiceImpl.java
  server/src/main/java/com/team_60/Mocco/security/dto/SecurityDto.java
  server/src/main/java/com/team_60/Mocco/study/dto/StudyDto.java
Labels: backend, fix

#164 [Feature] filter error handler
  server/build.gradle
  server/src/main/java/com/team_60/Mocco/alarm/controller/AlarmController.java
  server/src/main/java/com/team_60/Mocco/comment/controller/CommentController.java
  server/src/main/java/com/team_60/Mocco/exception/businessLogic/ExceptionCode.java
  server/src/main/java/com/team_60/Mocco/helper/aop/AuthenticationService.java
  server/src/main/java/com/team_60/Mocco/helper/aop/AuthenticationServiceLocal.java
  server/src/main/java/com/team_60/Mocco/helper/auth/AuthenticationService.java
  server/src/main/java/com/team_60/Mocco/helper/auth/AuthenticationServiceDeploy.java
  server/src/main/java/com/team_60/Mocco/helper/auth/AuthenticationServiceLocal.java
  server/src/main/java/com/team_60/Mocco/helper/interceptor/IdRequired.java
  server/src/main/java/com/team_60/Mocco/helper/interceptor/TokenInterceptor.java
  server/src/main/java/com/team_60/Mocco/member/controller/MemberController.java
  server/src/main/java/com/team_60/Mocco/member/controller/MemberSubController.java
  server/src/main/java/com/team_60/Mocco/proposal/controller/ProposalController.java
  server/src/main/java/com/team_60/Mocco/reply/controller/ReplyController.java
  server/src/main/java/com/team_60/Mocco/security/config/SecurityConfig.java
  server/src/main/java/com/team_60/Mocco/security/config/SecurityUtil.java
  server/src/main/java/com/team_60/Mocco/security/config/WebConfig.java
  server/src/main/java/com/team_60/Mocco/security/cotroller/SecurityController.java
  server/src/main/java/com/team_60/Mocco/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/team_60/Mocco/security/filter/JwtConstants.java
  server/src/main/java/com/team_60/Mocco/security/filter/JwtTokenProvider.java
  server/src/main/java/com/team_60/Mocco/security/handler/CustomAuthenticationEntryPoint.java
  server/src/main/java/com/team_60/Mocco/security/handler/FailureHandler.java
  server/src/main/java/com/team_60/Mocco/security/handler/OAuth2SuccessHandler.java
  server/src/main/java/com/team_60/Mocco/security/service/SecurityService.java
  server/src/main/java/com/team_60/Mocco/study/controller/StudyBoardController.java
  server/src/main/java/com/team_60/Mocco/study/controller/StudyEvaluationController.java
  server/src/main/java/com/team_60/Mocco/study/controller/StudyProgressController.java
  server/src/main/java/com/team_60/Mocco/study/dto/StudyDto.java
  server/src/main/java/com/team_60/Mocco/study/service/StudyServiceImpl.java
  server/src/main/java/com/team_60/Mocco/task_check/controller/TaskCheckController.java
Labels: backend

#162 [fix] 슬라이드 오류 해결, 스터디 카드 클릭 시 처리 수정 스터디 평가 모달 반응형, 프로필 별점 수정
  client/src/App.js
  client/src/components/PageComponent/Main/Evaluation/EvalueModal.js
  client/src/components/PageComponent/Main/Evaluation/Star.js
  client/src/components/PageComponent/Main/GitHubRepo.js
  client/src/components/PageComponent/Main/MyProfile.js
  client/src/components/PageComponent/Main/MyStudyList/Carousel.js
  client/src/components/PageComponent/Main/MyStudyList/ProgressList.js
  client/src/components/PageComponent/StudyBoard/TaskBox/TaskBox.js
  client/src/pages/StudyBoard.js
Labels: frontend, fix

#163 [Fix] studyboard 페이지 task 관련 오류 수정
  client/src/components/PageComponent/StudyBoard/AuthTask/AuthTask.js
  client/src/components/PageComponent/StudyBoard/AuthTask/AuthTaskModal.js
  client/src/components/PageComponent/StudyBoard/TaskBox/TaskBox.js
  client/src/components/PageComponent/StudyBoard/TaskBox/TaskItem.js
Labels: frontend

#161 [Feat] 프로필 레이어 팝업 알람 작업
  client/src/components/Common/Header/Alarm.js
  client/src/components/Common/Header/Header.js
  client/src/components/Common/Header/ProfileModal.js
Labels: frontend

#166 [fix] ProgressBar 유즈이펙트 의존성 배열 추가, 1260px, 패딩 1rem 줌
  client/public/assets/배경.png
  client/src/asset/모꼬배경.png
  client/src/components/PageComponent/StudyBoard/Progress/ProgressBar.js
  client/src/pages/Main.js
Labels: fix

#167 [Feat] 스터디 공고 리스트 반응형 작업
  client/.env
  client/package.json
  client/src/App.js
  client/src/api/index.js
  client/src/components/PageComponent/StudyBoard/TaskBox/TaskBox.js
  client/src/components/PageComponent/StudyList/MakeStudyButton.js
  client/src/components/PageComponent/StudyList/StudyCard.js
  client/src/components/PageComponent/StudyList/StudyListTitle.js
  client/src/pages/StudyList.js
Labels: frontend

#168 [Fix] 비로그인시 헤더의 마이페이지 버튼 비활성화
  client/src/components/Common/Header/Header.js
  client/src/components/Common/Header/ProfileModal.js
Labels: frontend, fix

#169 [Front]Auth 기능 구현
  client/src/App.js
  client/src/api/index.js
  client/src/components/Common/Header/Header.js
  client/src/components/Common/authentication/PrivateRoute.js
  client/src/components/Common/authentication/PublicRoute.js
  client/src/hoc/withPrivateRoute.js
  client/src/pages/FindPassword.js
  client/src/pages/Landing.js
  client/src/pages/LogIn.js
  client/src/pages/ModifyUser.js
  client/src/pages/SignUp.js
  client/src/utils/setAuthorizationToken.js
Labels: frontend, fix

#171 [Fix] oauth 로그인 restClient 이용하여 구현, refresh 오류 수정
  server/src/main/java/com/team_60/Mocco/helper/interceptor/TokenInterceptor.java
  server/src/main/java/com/team_60/Mocco/security/cotroller/SecurityController.java
  server/src/main/java/com/team_60/Mocco/security/dto/SecurityDto.java
  server/src/main/java/com/team_60/Mocco/security/filter/JwtConstants.java
  server/src/main/java/com/team_60/Mocco/security/filter/JwtTokenProvider.java
  server/src/main/java/com/team_60/Mocco/security/service/SecurityService.java
Labels: backend

#172 [Frontend]/로그인 로직 수정 및 API 주소 변경
  client/src/components/PageComponent/ModifyUser/ChangePasswordModal.js
  client/src/components/PageComponent/ModifyUser/WithdrawalModal.js
  client/src/pages/LogIn.js
  client/src/pages/ModifyUser.js
Labels: fix

#174 fix : interceptor 로직 오류 수정, api 수정
  server/src/main/java/com/team_60/Mocco/comment/controller/CommentController.java
  server/src/main/java/com/team_60/Mocco/exception/businessLogic/ExceptionCode.java
  server/src/main/java/com/team_60/Mocco/helper/auth/AuthenticationService.java
  server/src/main/java/com/team_60/Mocco/helper/auth/AuthenticationServiceDeploy.java
  server/src/main/java/com/team_60/Mocco/helper/auth/AuthenticationServiceLocal.java
  server/src/main/java/com/team_60/Mocco/helper/interceptor/TokenInterceptor.java
  server/src/main/java/com/team_60/Mocco/proposal/controller/ProposalController.java
  server/src/main/java/com/team_60/Mocco/security/config/SecurityConfig.java
  server/src/main/java/com/team_60/Mocco/security/config/WebConfig.java
  server/src/main/java/com/team_60/Mocco/security/filter/JwtAuthenticationFilter.java
Labels: backend

#175 [Frontend]로그인 로직 수정
  client/src/App.js
  client/src/pages/Landing.js
  client/src/pages/LogIn.js
Labels: frontend, fix

#173 [Fix]mypage API 변경
  client/src/App.js
  client/src/components/PageComponent/Main/Evaluation/EvalueModal.js
  client/src/components/PageComponent/Main/MyStudyList/ProgressList.js
  client/src/pages/Callback.js
  client/src/pages/StudyBoard.js
Labels: frontend, fix

#177 [Style] header 반응형 작업
  client/src/components/Common/Header/Header.js
  client/src/components/Common/Header/ProfileModal.js
  client/src/components/PageComponent/StudyList/StudyCard.js
Labels: frontend

#180 [Frontend] userInfo atom 로직 수정, 비밀번호 확인 유효성 검사기능 구현 및 로그인,회원가입 페이지 Style 작업
  client/src/App.js
  client/src/api/index.js
  client/src/components/Common/Header/Header.js
  client/src/pages/LogIn.js
  client/src/pages/ModifyUser.js
  client/src/pages/SignUp.js
  client/src/styles/reset.js
Labels: frontend, fix

#181 [fix] 스터디 생성 버그 수정
  client/src/App.js
  client/src/components/PageComponent/MakeStudy/Task.js
  client/src/pages/MakeStudy.js
Labels: frontend

#184 [Fix] studyBoard taskbox 관련 에러 수정 및 모달 반응형 작업
  client/src/App.js
  client/src/components/Common/ModalContent.js
  client/src/components/PageComponent/ModifyStudy/ModifyStudySection.js
  client/src/components/PageComponent/ModifyStudy/ModifyTaskSection.js
  client/src/components/PageComponent/StudyBoard/AuthTask/AuthTask.js
  client/src/components/PageComponent/StudyBoard/AuthTask/AuthTaskModal.js
  client/src/components/PageComponent/StudyBoard/Progress/ProgressBar.js
  client/src/components/PageComponent/StudyBoard/Progress/ProgressSection.js
  client/src/components/PageComponent/StudyBoard/StudyRuleModal.js
  client/src/components/PageComponent/StudyBoard/TaskBox/SelectUser.js
  client/src/components/PageComponent/StudyBoard/TaskBox/TaskBox.js
  client/src/components/PageComponent/StudyBoard/TaskBox/TaskItem.js
  client/src/components/PageComponent/StudyBoard/TaskBox/UserProgressBar.js
  client/src/components/PageComponent/StudyListDetail/ProposalTab/InputProposal.js
  client/src/components/PageComponent/StudyListDetail/QuestionTab/InputComment.js
  client/src/components/PageComponent/StudyListDetail/QuestionTab/InputReply.js
  client/src/pages/StudyBoard.js
  client/src/styles/reset.js
Labels: frontend, fix

#183 [Feat] landing 페이지, 반응형 구현
  client/src/App.js
  client/src/asset/랜딩모바일.png
  client/src/asset/스터디사진1.png
  client/src/asset/스터디사진2.png
  client/src/components/PageComponent/Landing/Component2.js
  client/src/components/PageComponent/Landing/DummyCard.js
  client/src/components/PageComponent/StudyBoard/TaskBox/TaskBox.js
  client/src/pages/Landing.js
Labels: frontend

#178 [Feature] Alarm 구독 API 및 기타 사항 수정
  server/src/main/java/com/team_60/Mocco/alarm/controller/AlarmController.java
  server/src/main/java/com/team_60/Mocco/alarm/service/AlarmService.java
  server/src/main/java/com/team_60/Mocco/alarm/service/AlarmServiceImpl.java
  server/src/main/java/com/team_60/Mocco/base_entity/BaseEntity.java
  server/src/main/java/com/team_60/Mocco/security/config/SecurityConfig.java
  server/src/main/java/com/team_60/Mocco/study/service/StudyServiceImpl.java
  server/src/main/java/com/team_60/Mocco/task_check/dto/TaskCheckDto.java
Labels: backend, fix

#185 [Fix]mypage, Callback 수정
  client/src/App.js
  client/src/components/PageComponent/Main/GitHubBtn/GitHubBtnGray.js
  client/src/components/PageComponent/Main/GitHubBtn/GitHubBtnMyGray.js
  client/src/components/PageComponent/Main/GitHubRepo.js
  client/src/components/PageComponent/Main/MyProfile.js
  client/src/components/PageComponent/Main/MyStudyList/Carousel.js
  client/src/components/PageComponent/Main/MyStudyList/StudyCard.js
  client/src/pages/Callback.js
  client/src/pages/LogIn.js
  client/src/pages/Main.js
Labels: frontend, fix

#186 [Style] footer 하단 고정 및 전반적인 style 수정
  client/src/App.js
  client/src/components/Common/Footer.js
  client/src/components/Common/Header/Header.js
  client/src/components/Common/Header/ProfileModal.js
  client/src/components/PageComponent/StudyList/StudyCard.js
  client/src/components/PageComponent/StudyListDetail/StudyMember.js
  client/src/pages/Landing.js
  client/src/pages/LogIn.js
  client/src/pages/Main.js
  client/src/pages/MakeStudy.js
  client/src/pages/ModifyStudy.js
  client/src/pages/ModifyUser.js
  client/src/pages/PrivacyPolicy.js
  client/src/pages/StudyBoard.js
  client/src/pages/StudyList.js
  client/src/pages/StudyListDetail.js
  client/src/pages/TermsOfUse.js
  client/src/styles/reset.js
Labels: frontend

#187 Feature/studyboard responsive
  client/src/components/PageComponent/StudyBoard/Progress/ProgressSection.js
  client/src/components/PageComponent/StudyBoard/TaskBox/SelectUser.js
  client/src/components/PageComponent/StudyBoard/TaskBox/TaskBox.js
  client/src/components/PageComponent/StudyBoard/TaskBox/UserProgressBar.js
  client/src/pages/Landing.js
  client/src/pages/StudyBoard.js
Labels: frontend

#188 [Fix] studyboard 페이지 드롭다운 아이콘 추가
  client/src/App.js
  client/src/components/PageComponent/StudyBoard/TaskBox/SelectUser.js
  client/src/components/PageComponent/StudyListDetail/StudyMember.js
Labels: frontend, fix

#189 [Fronted]longin, signup page style 작업 및 비밀번호 유효성 검사 수정
  client/src/App.js
  client/src/components/PageComponent/ModifyUser/ModifyUserInput.js
  client/src/pages/LogIn.js
  client/src/pages/ModifyUser.js
Labels: frontend, fix

#190 [Feature]로그인페이지 회원가입페이지 style 및 회원가입 에러수정
  client/src/App.js
  client/src/pages/LogIn.js
  client/src/pages/SignUp.js
  client/src/styles/reset.js
Labels: frontend, fix

#191 [fix] 회원정보수정페이지 이미지 업로드 에러 수정
  client/src/pages/ModifyUser.js
Labels: frontend, fix

#192 fix: 이미지 업로드 기능
  client/src/pages/ModifyUser.js
Labels: frontend, fix

#194 [Fix] 이미지 업로드 할 시 상태 업데이트 안되는 버그 수정
  client/src/App.js
  client/src/pages/MakeStudy.js
Labels: frontend, fix

#195 [Fix] ModifyStudy에서 jpeg도 업로드할 수 있도록 구현
  client/src/components/PageComponent/ModifyStudy/ModifyStudySection.js
  client/src/components/PageComponent/StudyListDetail/StudySection.js
Labels: frontend, fix

#196 [Feature]로그인, 회원가입 페이지 router 작업
  client/src/App.js
  client/src/pages/LogIn.js
  client/src/pages/SignUp.js
Labels: frontend

#197 [Fix] myPage: ShortList(4개 미만 스터디리스트 컴포넌트) 오류 해결, Callback 깃헙 연동 시 에러 처리 수정
  client/src/components/PageComponent/Main/MyStudyList/ProgressList.js
  client/src/components/PageComponent/Main/MyStudyList/ShortListSection.js
  client/src/pages/Callback.js
Labels: frontend, fix

#198 [Fix] 스터디 만든 유저와 로그인한 유저가 동일할 때만 '스터디장' 표시가 뜨도록 고침
  client/src/components/PageComponent/StudyListDetail/QuestionTab/CommentSection.js
  client/src/components/PageComponent/StudyListDetail/QuestionTab/ReplyItem.js
  client/src/components/PageComponent/StudyListDetail/StudySection.js
Labels: frontend, fix

#199 [frontend] 회원정보 수정 후 확인 alert 추가
  client/src/pages/ModifyUser.js
Labels: fix

#200 [Style] 각종 스타일 수정
  client/src/components/Common/Header/Header.js
  client/src/components/PageComponent/StudyList/SearchBar.js
  client/src/components/PageComponent/StudyList/StudyCard.js
  client/src/components/PageComponent/StudyList/StudyListTitle.js
  client/src/pages/Landing.js
  client/src/pages/StudyList.js
Labels: frontend, fix

#201 [Fix]/mypage, landing, studyBoard
  client/src/App.js
  client/src/components/Common/Button.js
  client/src/components/PageComponent/Landing/DummyCard.js
  client/src/components/PageComponent/Main/GitHubRepo.js
  client/src/components/PageComponent/StudyBoard/TaskBox/SelectUser.js
  client/src/components/PageComponent/StudyBoard/TaskBox/UserProgressBar.js
  client/src/pages/Landing.js
Labels: fix

#202 [Fix] studyboard 페이지 드롭다운, 모달 수정
  client/src/components/PageComponent/StudyBoard/AuthTask/AuthTaskModal.js
  client/src/components/PageComponent/StudyBoard/TaskBox/SelectUser.js
  client/src/components/PageComponent/StudyBoard/TaskBox/TaskBox.js
  client/src/components/PageComponent/StudyListDetail/StudyMember.js
  client/src/components/PageComponent/StudyListDetail/StudySection.js
Labels: frontend, fix

#203 [Feature]GitHub Oauth login 구현
  client/src/App.js
  client/src/pages/GithubOauthCallback.js
  client/src/pages/LogIn.js
Labels: frontend

#204 [Feature]refresh token 기능 구현
  client/src/api/index.js
Labels: frontend

#206 [Feature] readme 1차 작성 완료
  README.md
Labels: document

#205 [Fix]로그인, 회원가입, 회원정보수정페이지 전반적인 수정작업
  client/src/App.js
  client/src/atom/atom.js
  client/src/components/Common/Header/Header.js
  client/src/components/PageComponent/ModifyUser/ModifyUserButton.js
  client/src/components/PageComponent/ModifyUser/WithdrawalModal.js
  client/src/pages/LogIn.js
  client/src/pages/ModifyUser.js
  client/src/pages/SignUp.js
Labels: frontend, fix

#207 Fix/Mypage, Landing 디테일 수정, callback 주소, 처리 수정
  client/.env
  client/src/App.js
  client/src/components/Common/CountUp.js
  client/src/components/PageComponent/Main/Evaluation/EvalueModal.js
  client/src/components/PageComponent/Main/Evaluation/Star.js
  client/src/components/PageComponent/Main/GitHubBtn/GitHubBtnBlue.js
  client/src/components/PageComponent/Main/GitHubBtn/GitHubBtnMyGray.js
  client/src/components/PageComponent/Main/GitHubRepo.js
  client/src/components/PageComponent/Main/MyIntro.js
  client/src/components/PageComponent/Main/MyProfile.js
  client/src/components/PageComponent/Main/MyStudyList/Carousel.js
  client/src/components/PageComponent/Main/MyStudyList/ProgressList.js
  client/src/components/PageComponent/Main/MyStudyList/StudyCard.js
  client/src/pages/Callback.js
  client/src/pages/Landing.js
Labels: fix

#208 [Fix] studyboard 반응형
  client/src/App.js
  client/src/components/Common/CountUp.js
  client/src/components/PageComponent/StudyBoard/Progress/ProgressBar.js
  client/src/components/PageComponent/StudyBoard/Progress/ProgressSection.js
  client/src/components/PageComponent/StudyBoard/TaskBox/SelectUser.js
  client/src/components/PageComponent/StudyBoard/TaskBox/TaskBox.js
  client/src/components/PageComponent/StudyBoard/TaskBox/TaskItem.js
  client/src/components/PageComponent/StudyBoard/TaskBox/UserProgressBar.js
  client/src/pages/Landing.js
Labels: fix

#209 [Fix] error handle case 추가
  server/src/main/java/com/team_60/Mocco/exception/businessLogic/BusinessLogicException.java
  server/src/main/java/com/team_60/Mocco/exception/businessLogic/ExceptionCode.java
  server/src/main/java/com/team_60/Mocco/helper/interceptor/TokenInterceptor.java
  server/src/main/java/com/team_60/Mocco/security/filter/JwtTokenProvider.java
Labels: backend

#210 [Fix] API 수정, SSE 비즈니스 로직 수정
  server/src/main/java/com/team_60/Mocco/alarm/service/AlarmServiceImpl.java
  server/src/main/java/com/team_60/Mocco/helper/sse/SseService.java
  server/src/main/java/com/team_60/Mocco/study_member/dto/StudyMemberDto.java
  server/src/main/java/com/team_60/Mocco/study_member/mapper/StudyMemberMapper.java
Labels: backend, fix

#211 [Fix] mocco account
  server/src/main/java/com/team_60/Mocco/helper/sse/SseService.java
  server/src/main/java/com/team_60/Mocco/security/config/SecurityConfig.java
  server/src/main/java/com/team_60/Mocco/security/service/SecurityService.java
Labels: backend

#212 [Fix]스터디 진행 메인 페이지 코드 변경, 스터디 기간 범위 변경
  server/src/main/java/com/team_60/Mocco/study/mapper/StudyProgressMapper.java
  server/src/main/java/com/team_60/Mocco/study/service/StudyServiceImpl.java
Labels: backend, fix

#213 [Frontend]임시비밀번호 전송 이메일 form style
  client/public/findPasswordForm.html
Labels: frontend

#214 [Fix]mypage, Landing
  client/src/App.js
  client/src/components/PageComponent/Main/Evaluation/EvalueModal.js
  client/src/components/PageComponent/Main/Evaluation/Star.js
  client/src/components/PageComponent/Main/MyProfile.js
  client/src/components/PageComponent/Main/MyStudyList/ProgressList.js
  client/src/components/PageComponent/Main/MyStudyList/ShortListSection.js
  client/src/components/PageComponent/Main/MyStudyList/StudyCard.js
  client/src/components/PageComponent/Main/ProfileStar.js
  client/src/components/PageComponent/StudyBoard/Progress/ProgressBar.js
  client/src/pages/Callback.js
  client/src/pages/Landing.js
  client/src/pages/Main.js
Labels: frontend, fix

#216 [Feat] 알림 클릭 스터디방 이동
  client/src/components/Common/Header/Alarm.js
  client/src/components/Common/Header/ProfileModal.js
  client/src/pages/MakeStudy.js
Labels: frontend

#217 [Feat] 프로필 레이어 팝업 바깥 클릭 시 닫힘
  client/src/components/Common/Header/Header.js
  client/src/components/Common/Header/ProfileModal.js
Labels: frontend

#218 [Fix] 알림 링크 studyId 오기입 수정
  client/src/components/Common/Header/Alarm.js
Labels: frontend, fix

#219 [Fix] studyboard 페이지 드롭다운에서 프로필사진 클릭 시 에러났던 것 수정
  client/src/components/PageComponent/StudyBoard/TaskBox/SelectUser.js
  client/src/components/PageComponent/StudyListDetail/ProposalTab/ProposalSection.js
  client/src/components/PageComponent/StudyListDetail/QuestionTab/CommentSection.js
  client/src/components/PageComponent/StudyListDetail/QuestionTab/InputComment.js
  client/src/components/PageComponent/StudyListDetail/QuestionTab/InputReply.js
  client/src/components/PageComponent/StudyListDetail/QuestionTab/QuestionTab.js
  client/src/components/PageComponent/StudyListDetail/QuestionTab/ReplyItem.js
Labels: frontend, fix

#221 [Feature] 비밀번호 찾기 시에 Template으로 이메일을 전송 [Fix] SSE unsubscribe, PrinicpalDetails
  server/build.gradle
  server/src/main/java/com/team_60/Mocco/helper/mail/sender/EmailSendable.java
  server/src/main/java/com/team_60/Mocco/helper/mail/sender/EmailSenderMock.java
  server/src/main/java/com/team_60/Mocco/helper/mail/sender/SimpleEmailSender.java
  server/src/main/java/com/team_60/Mocco/helper/password/NewPasswordManager.java
  server/src/main/java/com/team_60/Mocco/helper/password/PasswordManagerImpl.java
  server/src/main/java/com/team_60/Mocco/helper/password/PasswordManagerMock.java
  server/src/main/java/com/team_60/Mocco/helper/sse/SseService.java
  server/src/main/java/com/team_60/Mocco/member/service/MemberServiceImpl.java
  server/src/main/java/com/team_60/Mocco/security/config/SecurityConfig.java
  server/src/main/java/com/team_60/Mocco/security/oauth/PrincipalDetails.java
  server/src/main/java/com/team_60/Mocco/test/TestController.java
  server/src/main/resources/templates/mail_password.html
Labels: backend

#220 [Fix] filter error
  server/src/main/java/com/team_60/Mocco/exception/businessLogic/ExceptionCode.java
  server/src/main/java/com/team_60/Mocco/helper/interceptor/TokenInterceptor.java
  server/src/main/java/com/team_60/Mocco/security/config/SecurityConfig.java
  server/src/main/java/com/team_60/Mocco/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/team_60/Mocco/security/service/SecurityService.java
Labels: backend

#223 Fix/mypage 깃헙 연동 로직 수정
  client/src/pages/Callback.js
  client/src/pages/Main.js
Labels: frontend, fix

#224 [Feat] 404 페이지 구현
  client/src/App.js
  client/src/pages/NotFound.js
Labels: frontend

#225 [Fix] mypage 반응형 css 수정
  client/src/components/PageComponent/Main/GitHubBtn/GitHubBtnBlue.js
  client/src/components/PageComponent/Main/GitHubBtn/GitHubBtnGray.js
  client/src/components/PageComponent/Main/GitHubBtn/GitHubBtnMyGray.js
  client/src/components/PageComponent/Main/GitHubRepo.js
  client/src/components/PageComponent/Main/MyStudyList/Carousel.js
  client/src/components/PageComponent/Main/MyStudyList/ProgressList.js
  client/src/pages/Callback.js
  client/src/pages/GithubOauthCallback.js
Labels: frontend, fix

#229 [Feat] Title 및 Favicon
  client/public/favicon.ico
  client/public/favicon/android-icon-144x144.png
  client/public/favicon/android-icon-192x192.png
  client/public/favicon/android-icon-36x36.png
  client/public/favicon/android-icon-48x48.png
  client/public/favicon/android-icon-72x72.png
  client/public/favicon/android-icon-96x96.png
  client/public/favicon/apple-icon-114x114.png
  client/public/favicon/apple-icon-120x120.png
  client/public/favicon/apple-icon-144x144.png
  client/public/favicon/apple-icon-152x152.png
  client/public/favicon/apple-icon-180x180.png
  client/public/favicon/apple-icon-57x57.png
  client/public/favicon/apple-icon-60x60.png
  client/public/favicon/apple-icon-72x72.png
  client/public/favicon/apple-icon-76x76.png
  client/public/favicon/apple-icon-precomposed.png
  client/public/favicon/apple-icon.png
  client/public/favicon/browserconfig.xml
  client/public/favicon/favicon-16x16.png
  client/public/favicon/favicon-32x32.png
  client/public/favicon/favicon-96x96.png
  client/public/favicon/favicon.ico
  client/public/favicon/ms-icon-144x144.png
  client/public/favicon/ms-icon-150x150.png
  client/public/favicon/ms-icon-310x310.png
  client/public/favicon/ms-icon-70x70.png
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
Labels: frontend

#231 [Frontend] 깃헙 소셜 로그인 및 회원정보 수정페이지 수정
  client/src/components/PageComponent/ModifyUser/ChangePasswordModal.js
  client/src/components/PageComponent/ModifyUser/ModifyUserButton.js
  client/src/components/PageComponent/ModifyUser/WithdrawalModal.js
  client/src/pages/GithubOauthCallback.js
  client/src/pages/ModifyUser.js
Labels: frontend, fix

#232 fix : mocco 계정 기능 막기
  server/src/main/java/com/team_60/Mocco/exception/businessLogic/ExceptionCode.java
  server/src/main/java/com/team_60/Mocco/helper/auth/AuthenticationServiceDeploy.java
  server/src/main/java/com/team_60/Mocco/helper/auth/AuthenticationServiceLocal.java
  server/src/main/java/com/team_60/Mocco/helper/interceptor/TokenInterceptor.java
  server/src/main/java/com/team_60/Mocco/helper/stub/StubData.java
  server/src/main/java/com/team_60/Mocco/security/config/SecurityConfig.java
  server/src/main/java/com/team_60/Mocco/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/team_60/Mocco/security/handler/CustomAuthenticationEntryPoint.java
Labels: backend

#233 [Feature] Validation 수정
  server/src/main/java/com/team_60/Mocco/proposal/dto/ProposalDto.java
  server/src/main/java/com/team_60/Mocco/task/dto/TaskDto.java
Labels: backend, fix

#234 [Feat] 공지사항 추가
  client/src/App.js
  client/src/components/PageComponent/Landing/Notice.js
Labels: frontend
