Repository codestates-seb/seb39_main_060, pull requests merged in 2022-09, with the labels that each got.

#3 feature : entity 생성 중
  server/.gitignore
  server/build.gradle
  server/gradle/wrapper/gradle-wrapper.jar
  server/gradle/wrapper/gradle-wrapper.properties
  server/gradlew
  server/gradlew.bat
  server/settings.gradle
  server/src/main/java/com/team_60/Mocco/MoccoApplication.java
  server/src/main/java/com/team_60/Mocco/alarm/entity/Alarm.java
  server/src/main/java/com/team_60/Mocco/audit/Auditable.java
  server/src/main/java/com/team_60/Mocco/chatting/entity/Chatting.java
  server/src/main/java/com/team_60/Mocco/chatting/entity/ChattingRoom.java
  server/src/main/java/com/team_60/Mocco/comment/entity/Comment.java
  server/src/main/java/com/team_60/Mocco/member/entity/Member.java
  server/src/main/java/com/team_60/Mocco/member/entity/MyInfo.java
  server/src/main/java/com/team_60/Mocco/proposal/entity/Proposal.java
  server/src/main/java/com/team_60/Mocco/reply/entity/Reply.java
  server/src/main/java/com/team_60/Mocco/study/entity/Study.java
  server/src/main/java/com/team_60/Mocco/study_member/entity/StudyMember.java
  server/src/main/java/com/team_60/Mocco/task/entity/Task.java
  server/src/main/java/com/team_60/Mocco/task_check/entity/TaskCheck.java
  server/src/main/java/com/team_60/Mocco/warning/entity/Warning.java
  server/src/main/resources/application.properties
  server/src/main/resources/application.yml
  server/src/test/java/com/team_60/Mocco/MoccoApplicationTests.java
Labels: backend

#5 Feature/entity
  server/.gitignore
  server/build.gradle
  server/gradle/wrapper/gradle-wrapper.jar
  server/gradle/wrapper/gradle-wrapper.properties
  server/gradlew
  server/gradlew.bat
  server/settings.gradle
  server/src/main/java/com/team_60/Mocco/MoccoApplication.java
  server/src/main/java/com/team_60/Mocco/alarm/entity/Alarm.java
  server/src/main/java/com/team_60/Mocco/audit/Auditable.java
  server/src/main/java/com/team_60/Mocco/chatting/entity/Chatting.java
  server/src/main/java/com/team_60/Mocco/chatting/entity/ChattingRoom.java
  server/src/main/java/com/team_60/Mocco/comment/entity/Comment.java
  server/src/main/java/com/team_60/Mocco/member/entity/Member.java
  server/src/main/java/com/team_60/Mocco/member/entity/MyInfo.java
  server/src/main/java/com/team_60/Mocco/proposal/entity/Proposal.java
  server/src/main/java/com/team_60/Mocco/reply/entity/Reply.java
  server/src/main/java/com/team_60/Mocco/study/entity/Study.java
  server/src/main/java/com/team_60/Mocco/study_member/entity/StudyMember.java
  server/src/main/java/com/team_60/Mocco/task/entity/Task.java
  server/src/main/java/com/team_60/Mocco/task_check/entity/TaskCheck.java
  server/src/main/java/com/team_60/Mocco/warning/entity/Warning.java
  server/src/main/resources/application.yml
  server/src/test/java/com/team_60/Mocco/MoccoApplicationTests.java
Labels: backend

#6 Revert 5 feature/entity
  .github/ISSUE_TEMPLATE/backend-task-template.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/document-template.md
  .github/ISSUE_TEMPLATE/etc-template.md
  .github/ISSUE_TEMPLATE/frontend-task-template.md
  server/.gitignore
  server/build.gradle
  server/gradle/wrapper/gradle-wrapper.jar
  server/gradle/wrapper/gradle-wrapper.properties
  server/gradlew
  server/gradlew.bat
  server/settings.gradle
  server/src/main/java/com/team_60/Mocco/MoccoApplication.java
  server/src/main/java/com/team_60/Mocco/alarm/entity/Alarm.java
  server/src/main/java/com/team_60/Mocco/audit/Auditable.java
  server/src/main/java/com/team_60/Mocco/chatting/entity/Chatting.java
  server/src/main/java/com/team_60/Mocco/chatting/entity/ChattingRoom.java
  server/src/main/java/com/team_60/Mocco/comment/entity/Comment.java
  server/src/main/java/com/team_60/Mocco/member/entity/Member.java
  server/src/main/java/com/team_60/Mocco/member/entity/MyInfo.java
  server/src/main/java/com/team_60/Mocco/proposal/entity/Proposal.java
  server/src/main/java/com/team_60/Mocco/reply/entity/Reply.java
  server/src/main/java/com/team_60/Mocco/study/entity/Study.java
  server/src/main/java/com/team_60/Mocco/study_member/entity/StudyMember.java
  server/src/main/java/com/team_60/Mocco/task/entity/Task.java
  server/src/main/java/com/team_60/Mocco/task_check/entity/TaskCheck.java
  server/src/main/java/com/team_60/Mocco/warning/entity/Warning.java
  server/src/main/resources/application.properties
  server/src/main/resources/application.yml
  server/src/test/java/com/team_60/Mocco/MoccoApplicationTests.java
Labels: backend

#13 Feature/cra
  client/.env
  client/.eslintrc.json
  client/.gitignore
  client/.prettierrc.json
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.js
  client/src/api/index.js
  client/src/components/Common/Button.js
  client/src/components/Common/Modal.js
  client/src/index.js
  client/src/pages/FindPassword.js
  client/src/pages/Landing.js
  client/src/pages/LogIn.js
  client/src/pages/Main.js
  client/src/pages/MakeStudy.js
  client/src/pages/ModifyUser.js
  client/src/pages/SignUp.js
  client/src/pages/StudyBoard.js
  client/src/pages/StudyList.js
  client/src/pages/StudyListDetail.js
Labels: frontend

#12 [Feat] Spring 에서 사용할 부가 기능 구현
  server/build.gradle
  server/src/main/java/com/team_60/Mocco/exception/businessLogic/BusinessLogicException.java
  server/src/main/java/com/team_60/Mocco/exception/businessLogic/ExceptionCode.java
  server/src/main/java/com/team_60/Mocco/helper/mail/configuration/EmailConfigurationDeployEnvironment.java
  server/src/main/java/com/team_60/Mocco/helper/mail/sender/EmailSendable.java
  server/src/main/java/com/team_60/Mocco/helper/mail/sender/EmailSenderMock.java
  server/src/main/java/com/team_60/Mocco/helper/mail/sender/SimpleEmailSender.java
  server/src/main/java/com/team_60/Mocco/helper/mail/test/TestController.java
  server/src/main/java/com/team_60/Mocco/helper/password/NewPasswordManager.java
  server/src/main/java/com/team_60/Mocco/helper/password/PasswordManagerImpl.java
  server/src/main/java/com/team_60/Mocco/helper/password/PasswordManagerMock.java
  server/src/main/java/com/team_60/Mocco/helper/upload/ImageUploadType.java
  server/src/main/java/com/team_60/Mocco/helper/upload/S3ImageUpload.java
  server/src/main/java/com/team_60/Mocco/helper/upload/S3ImageUploadImpl.java
  server/src/main/java/com/team_60/Mocco/helper/upload/S3ImageUploadMock.java
  server/src/main/resources/application-deploy.yml
  server/src/main/resources/application.properties
  server/src/main/resources/application.yml
Labels: backend

#16 Feature/security
  server/build.gradle
  server/src/main/java/com/team_60/Mocco/member/entity/Member.java
  server/src/main/java/com/team_60/Mocco/member/repository/MemberRepository.java
  server/src/main/java/com/team_60/Mocco/security/config/RedisRepositoryConfig.java
  server/src/main/java/com/team_60/Mocco/security/config/SecurityConfig.java
  server/src/main/java/com/team_60/Mocco/security/config/SecurityUtil.java
  server/src/main/java/com/team_60/Mocco/security/config/WebConfig.java
  server/src/main/java/com/team_60/Mocco/security/cotroller/SecurityController.java
  server/src/main/java/com/team_60/Mocco/security/dto/Request.java
  server/src/main/java/com/team_60/Mocco/security/dto/Response.java
  server/src/main/java/com/team_60/Mocco/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/team_60/Mocco/security/filter/JwtConstants.java
  server/src/main/java/com/team_60/Mocco/security/filter/JwtTokenProvider.java
  server/src/main/java/com/team_60/Mocco/security/oauth/PrincipalDetails.java
  server/src/main/java/com/team_60/Mocco/security/oauth/PrincipalDetailsService.java
  server/src/main/java/com/team_60/Mocco/security/service/SecurityService.java
  server/src/main/resources/application.yml
Labels: backend

#17 [Feat]setting fix
  .babelrc
  client/.eslintrc.json
  client/.prettierrc.json
  client/craco.config.js
  craco.config.js
Labels: frontend, fix

#18 [Feat] Member 관련 기능 구현
  server/build.gradle
  server/src/main/java/com/team_60/Mocco/dto/MultiResponseDto.java
  server/src/main/java/com/team_60/Mocco/dto/SingleResponseDto.java
  server/src/main/java/com/team_60/Mocco/exception/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/team_60/Mocco/exception/businessLogic/ExceptionCode.java
  server/src/main/java/com/team_60/Mocco/exception/dto/ErrorMapper.java
  server/src/main/java/com/team_60/Mocco/exception/dto/ErrorResponse.java
  server/src/main/java/com/team_60/Mocco/helper/test/TestController.java
  server/src/main/java/com/team_60/Mocco/member/controller/MemberController.java
  server/src/main/java/com/team_60/Mocco/member/controller/MemberControllerNotSecured.java
  server/src/main/java/com/team_60/Mocco/member/controller/MemberSubController.java
  server/src/main/java/com/team_60/Mocco/member/dto/MemberDto.java
  server/src/main/java/com/team_60/Mocco/member/entity/Member.java
  server/src/main/java/com/team_60/Mocco/member/entity/MyInfo.java
  server/src/main/java/com/team_60/Mocco/member/mapper/MemberMapper.java
  server/src/main/java/com/team_60/Mocco/member/repository/MemberRepository.java
  server/src/main/java/com/team_60/Mocco/member/service/MemberService.java
  server/src/main/java/com/team_60/Mocco/member/service/MemberServiceImpl.java
  server/src/main/java/com/team_60/Mocco/study/dto/StudyDto.java
  server/src/main/java/com/team_60/Mocco/study/entity/Study.java
  server/src/main/java/com/team_60/Mocco/study/mapper/StudyMapper.java
  server/src/main/java/com/team_60/Mocco/study_member/entity/StudyMember.java
Labels: backend

#20 Feature/marge be
  server/src/main/java/com/team_60/Mocco/alarm/entity/Alarm.java
  server/src/main/java/com/team_60/Mocco/chatting/entity/Chatting.java
  server/src/main/java/com/team_60/Mocco/chatting/entity/ChattingRoom.java
  server/src/main/java/com/team_60/Mocco/comment/entity/Comment.java
  server/src/main/java/com/team_60/Mocco/member/controller/MemberControllerNotSecured.java
  server/src/main/java/com/team_60/Mocco/member/entity/Member.java
  server/src/main/java/com/team_60/Mocco/member/service/MemberServiceImpl.java
  server/src/main/java/com/team_60/Mocco/proposal/entity/Proposal.java
  server/src/main/java/com/team_60/Mocco/reply/entity/Reply.java
  server/src/main/java/com/team_60/Mocco/security/cotroller/SecurityController.java
  server/src/main/java/com/team_60/Mocco/security/service/SecurityService.java
  server/src/main/java/com/team_60/Mocco/task/entity/Task.java
  server/src/main/java/com/team_60/Mocco/task_check/entity/TaskCheck.java
  server/src/main/java/com/team_60/Mocco/test/TestController.java
  server/src/main/java/com/team_60/Mocco/warning/entity/Warning.java
Labels: backend

#24 feature : 잘못된 로그인 시 에러 메세지 전송 기능
  server/src/main/java/com/team_60/Mocco/exception/businessLogic/ExceptionCode.java
  server/src/main/java/com/team_60/Mocco/security/filter/JwtTokenProvider.java
  server/src/main/java/com/team_60/Mocco/security/oauth/PrincipalDetailsService.java
  server/src/main/java/com/team_60/Mocco/security/service/SecurityService.java
Labels: backend

#26 feature : study_board_CRUD 작업 중 중간 머지
  server/src/main/java/com/team_60/Mocco/exception/businessLogic/ExceptionCode.java
  server/src/main/java/com/team_60/Mocco/member/entity/Member.java
  server/src/main/java/com/team_60/Mocco/study/controller/StudyBoardController.java
  server/src/main/java/com/team_60/Mocco/study/controller/StudyInfoController.java
  server/src/main/java/com/team_60/Mocco/study/dto/StudyDto.java
  server/src/main/java/com/team_60/Mocco/study/entity/Study.java
  server/src/main/java/com/team_60/Mocco/study/mapper/StudyMapper.java
  server/src/main/java/com/team_60/Mocco/study/repository/StudyRepository.java
  server/src/main/java/com/team_60/Mocco/study/service/StudyService.java
  server/src/main/java/com/team_60/Mocco/study/service/StudyServiceImpl.java
Labels: backend

#27 Feature/comment api
  server/src/main/java/com/team_60/Mocco/comment/controller/CommentController.java
  server/src/main/java/com/team_60/Mocco/comment/dto/CommentDto.java
  server/src/main/java/com/team_60/Mocco/comment/mapper/CommentMapper.java
  server/src/main/java/com/team_60/Mocco/comment/repository/CommentRepository.java
  server/src/main/java/com/team_60/Mocco/comment/service/CommentService.java
  server/src/main/java/com/team_60/Mocco/comment/service/CommentServiceImpl.java
  server/src/main/java/com/team_60/Mocco/exception/businessLogic/ExceptionCode.java
  server/src/main/java/com/team_60/Mocco/member/dto/MemberDto.java
  server/src/main/java/com/team_60/Mocco/member/mapper/MemberMapper.java
  server/src/main/java/com/team_60/Mocco/reply/controller/ReplyController.java
  server/src/main/java/com/team_60/Mocco/reply/dto/ReplyDto.java
  server/src/main/java/com/team_60/Mocco/reply/mapper/ReplyMapper.java
  server/src/main/java/com/team_60/Mocco/reply/repository/ReplyRepository.java
  server/src/main/java/com/team_60/Mocco/reply/service/ReplyService.java
  server/src/main/java/com/team_60/Mocco/reply/service/ReplyServiceImpl.java
  server/src/main/java/com/team_60/Mocco/study/service/StudyService.java
  server/src/main/java/com/team_60/Mocco/study/service/StudyServiceImpl.java
Labels: backend

#29 [Feat] Reply 관련 API 완성, Proposal 관련 API 구현 완료
  server/src/main/java/com/team_60/Mocco/comment/service/CommentServiceImpl.java
  server/src/main/java/com/team_60/Mocco/exception/businessLogic/ExceptionCode.java
  server/src/main/java/com/team_60/Mocco/member/entity/Member.java
  server/src/main/java/com/team_60/Mocco/proposal/controller/ProposalController.java
  server/src/main/java/com/team_60/Mocco/proposal/dto/ProposalDto.java
  server/src/main/java/com/team_60/Mocco/proposal/entity/Proposal.java
  server/src/main/java/com/team_60/Mocco/proposal/mapper/ProposalMapper.java
  server/src/main/java/com/team_60/Mocco/proposal/repository/ProposalRepository.java
  server/src/main/java/com/team_60/Mocco/proposal/service/ProposalService.java
  server/src/main/java/com/team_60/Mocco/proposal/service/ProposalServiceImpl.java
  server/src/main/java/com/team_60/Mocco/reply/service/ReplyServiceImpl.java
  server/src/main/java/com/team_60/Mocco/study/controller/StudyBoardController.java
  server/src/main/java/com/team_60/Mocco/study/controller/StudyInfoController.java
  server/src/main/java/com/team_60/Mocco/study/service/StudyServiceImpl.java
  server/src/main/java/com/team_60/Mocco/study_member/repository/StudyMemberRepository.java
  server/src/main/java/com/team_60/Mocco/study_member/serive/StudyMemberService.java
  server/src/main/java/com/team_60/Mocco/study_member/serive/StudyMemberServiceImpl.java
Labels: backend

#30 feature : study post,patch,delete 기능 구현, get 구현중
  server/src/main/java/com/team_60/Mocco/exception/businessLogic/ExceptionCode.java
  server/src/main/java/com/team_60/Mocco/member/dto/MemberDto.java
  server/src/main/java/com/team_60/Mocco/member/service/MemberServiceImpl.java
  server/src/main/java/com/team_60/Mocco/security/filter/JwtTokenProvider.java
  server/src/main/java/com/team_60/Mocco/study/controller/StudyBoardController.java
  server/src/main/java/com/team_60/Mocco/study/controller/StudyInfoController.java
  server/src/main/java/com/team_60/Mocco/study/dto/StudyDto.java
  server/src/main/java/com/team_60/Mocco/study/entity/Study.java
  server/src/main/java/com/team_60/Mocco/study/mapper/StudyMapper.java
  server/src/main/java/com/team_60/Mocco/study/repository/StudyRepository.java
  server/src/main/java/com/team_60/Mocco/study/service/StudyService.java
  server/src/main/java/com/team_60/Mocco/study/service/StudyServiceImpl.java
  server/src/main/java/com/team_60/Mocco/task/dto/TaskDto.java
  server/src/main/java/com/team_60/Mocco/task/mapper/TaskMapper.java
Labels: backend

#38 Fix/global css
  client/src/index.js
  client/src/styles/reset.js
Labels: frontend, fix

#40 feature : 날짜 범위 지정, dto 수정, capacity 수정
  server/src/main/java/com/team_60/Mocco/comment/service/CommentServiceImpl.java
  server/src/main/java/com/team_60/Mocco/dto/exception/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/team_60/Mocco/dto/exception/businessLogic/BusinessLogicException.java
  server/src/main/java/com/team_60/Mocco/dto/exception/businessLogic/ExceptionCode.java
  server/src/main/java/com/team_60/Mocco/dto/exception/dto/ErrorMapper.java
  server/src/main/java/com/team_60/Mocco/dto/exception/dto/ErrorResponse.java
  server/src/main/java/com/team_60/Mocco/exception/dto/ErrorMapper.java
  server/src/main/java/com/team_60/Mocco/helper/password/PasswordManagerImpl.java
  server/src/main/java/com/team_60/Mocco/helper/password/PasswordManagerMock.java
  server/src/main/java/com/team_60/Mocco/member/service/MemberServiceImpl.java
  server/src/main/java/com/team_60/Mocco/proposal/service/ProposalServiceImpl.java
  server/src/main/java/com/team_60/Mocco/reply/service/ReplyServiceImpl.java
  server/src/main/java/com/team_60/Mocco/security/filter/JwtTokenProvider.java
  server/src/main/java/com/team_60/Mocco/security/oauth/PrincipalDetailsService.java
  server/src/main/java/com/team_60/Mocco/security/service/SecurityService.java
  server/src/main/java/com/team_60/Mocco/study/dto/StudyDto.java
  server/src/main/java/com/team_60/Mocco/study/mapper/StudyMapper.java
  server/src/main/java/com/team_60/Mocco/study/service/StudyServiceImpl.java
  server/src/main/java/com/team_60/Mocco/study_member/serive/StudyMemberServiceImpl.java
  server/src/main/java/com/team_60/Mocco/task/controller/TaskController.java
  server/src/main/java/com/team_60/Mocco/task/dto/TaskDto.java
  server/src/main/java/com/team_60/Mocco/task/mapper/TaskMapper.java
  server/src/main/java/com/team_60/Mocco/task/repository/TaskRepository.java
  server/src/main/java/com/team_60/Mocco/task/service/TaskService.java
  server/src/main/java/com/team_60/Mocco/task/service/TaskServiceImpl.java
Labels: backend

#42 [Feat] mypage read 레이아웃, 스타일 작업
  client/.eslintrc.json
  client/src/components/PageComponent/Main/Component4.js
  client/src/components/PageComponent/Main/GitHubRepo.js
  client/src/components/PageComponent/Main/MyIntro.js
  client/src/components/PageComponent/Main/MyProfile.js
  client/src/components/PageComponent/Main/TotalContainer.js
  client/src/pages/Main.js
Labels: frontend

#45 [Feature]회원가입, 로그인 기능구현 및 로그인 view 구현
  client/src/asset/profile.png
  client/src/components/Common/Avatar.js
  client/src/pages/LogIn.js
  client/src/pages/SignUp.js
Labels: frontend

#50 [Feat] : database 연결, stub data 저장
  server/build.gradle
  server/src/main/java/com/team_60/Mocco/helper/stub/StubData.java
  server/src/main/java/com/team_60/Mocco/member/entity/Member.java
  server/src/main/java/com/team_60/Mocco/study/controller/StudyBoardController.java
  server/src/main/java/com/team_60/Mocco/study/dto/StudyDto.java
  server/src/main/java/com/team_60/Mocco/study/mapper/StudyMapper.java
  server/src/main/java/com/team_60/Mocco/study/service/StudyService.java
  server/src/main/java/com/team_60/Mocco/study/service/StudyServiceImpl.java
  server/src/main/java/com/team_60/Mocco/task/dto/TaskDto.java
  server/src/main/java/com/team_60/Mocco/task/entity/Task.java
  server/src/main/java/com/team_60/Mocco/test/TestController.java
  server/src/main/resources/application-dev.yml
  server/src/main/resources/application.yml
Labels: backend

#51 Feature/study progress api
  server/src/main/java/com/team_60/Mocco/dto/exception/businessLogic/ExceptionCode.java
  server/src/main/java/com/team_60/Mocco/study/controller/StudyBoardController.java
  server/src/main/java/com/team_60/Mocco/study/controller/StudyProgressController.java
  server/src/main/java/com/team_60/Mocco/study/dto/StudyProgressDto.java
  server/src/main/java/com/team_60/Mocco/study/mapper/StudyProgressMapper.java
  server/src/main/java/com/team_60/Mocco/study/service/StudyProgressService.java
  server/src/main/java/com/team_60/Mocco/study/service/StudyProgressServiceImpl.java
  server/src/main/java/com/team_60/Mocco/study/service/StudyService.java
  server/src/main/java/com/team_60/Mocco/study/service/StudyServiceImpl.java
  server/src/main/java/com/team_60/Mocco/task/dto/TaskDto.java
  server/src/main/java/com/team_60/Mocco/task/mapper/TaskMapper.java
  server/src/main/java/com/team_60/Mocco/task_check/controller/TaskCheckController.java
  server/src/main/java/com/team_60/Mocco/task_check/dto/TaskCheckDto.java
  server/src/main/java/com/team_60/Mocco/task_check/mapper/TaskCheckMapper.java
  server/src/main/java/com/team_60/Mocco/task_check/repository/TaskCheckRepository.java
  server/src/main/java/com/team_60/Mocco/task_check/service/TaskCheckService.java
  server/src/main/java/com/team_60/Mocco/task_check/service/TaskCheckServiceImpl.java
  server/src/main/java/com/team_60/Mocco/test/TestController.java
Labels: backend

#52 [Fix] : database 오류 수정
  .gitignore
  server/src/main/resources/application-dev.yml
  server/src/main/resources/application-local.yml
  server/src/main/resources/application.yml
Labels: backend

#54 [Feat] 버튼 컴포넌트 구현
  client/package.json
  client/src/components/Common/Button.js
  client/src/components/PageComponent/StudyListDetail/ProposaTab.js
  client/src/components/PageComponent/StudyListDetail/QuestionTab.js
  client/src/components/PageComponent/StudyListDetail/StudySection.js
Labels: frontend

#60 [Feature] 리코일 폴더, 파일 생성 및 초기 세팅 구현
  client/src/atom/atom.js
  client/src/components/PageComponent/StudyListDetail/DeletedComment.js
  client/src/components/PageComponent/StudyListDetail/ProposaTab.js
  client/src/components/PageComponent/StudyListDetail/ProposalTab/ProposaTab.js
  client/src/components/PageComponent/StudyListDetail/QuestionTab/CommentSection.js
  client/src/components/PageComponent/StudyListDetail/QuestionTab/InputComment.js
  client/src/components/PageComponent/StudyListDetail/QuestionTab/QuestionTab.js
  client/src/components/PageComponent/StudyListDetail/QuestionTab/ReplySection.js
  client/src/components/PageComponent/StudyListDetail/TabSection.js
  client/src/index.js
  client/src/pages/StudyListDetail.js
Labels: frontend

#57 feature : scheduler 기능
  server/src/main/java/com/team_60/Mocco/MoccoApplication.java
  server/src/main/java/com/team_60/Mocco/dto/exception/businessLogic/ExceptionCode.java
  server/src/main/java/com/team_60/Mocco/dto/exception/dto/ErrorResponse.java
  server/src/main/java/com/team_60/Mocco/helper/scheduler/Scheduler.java
  server/src/main/java/com/team_60/Mocco/helper/scheduler/SchedulerConfig.java
  server/src/main/java/com/team_60/Mocco/security/config/SecurityConfig.java
  server/src/main/java/com/team_60/Mocco/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/team_60/Mocco/study/repository/StudyRepository.java
  server/src/main/java/com/team_60/Mocco/study_member/repository/StudyMemberRepository.java
  server/src/main/java/com/team_60/Mocco/test/TestController.java
Labels: backend

#64 [Feat] 스터디 종료 후, 평가 API 구현
  server/src/main/java/com/team_60/Mocco/dto/exception/businessLogic/ExceptionCode.java
  server/src/main/java/com/team_60/Mocco/member/dto/MemberDto.java
  server/src/main/java/com/team_60/Mocco/member/mapper/MemberMapper.java
  server/src/main/java/com/team_60/Mocco/study/controller/StudyEvaluationController.java
  server/src/main/java/com/team_60/Mocco/study/dto/StudyDto.java
  server/src/main/java/com/team_60/Mocco/study/dto/StudyEvaluationDto.java
  server/src/main/java/com/team_60/Mocco/study/mapper/StudyEvaluationMapper.java
  server/src/main/java/com/team_60/Mocco/study/mapper/StudyMapper.java
  server/src/main/java/com/team_60/Mocco/study/service/StudyEvaluationService.java
  server/src/main/java/com/team_60/Mocco/study/service/StudyEvaluationServiceImpl.java
  server/src/main/java/com/team_60/Mocco/study_member/dto/StudyMemberDto.java
  server/src/main/java/com/team_60/Mocco/study_member/mapper/StudyMemberMapper.java
  server/src/main/java/com/team_60/Mocco/test/TestController.java
Labels: backend

#65 feature : study count API 구현
  server/src/main/java/com/team_60/Mocco/member/repository/MemberRepository.java
  server/src/main/java/com/team_60/Mocco/security/config/SecurityConfig.java
  server/src/main/java/com/team_60/Mocco/study/controller/StudyInfoController.java
  server/src/main/java/com/team_60/Mocco/study/dto/StudyDto.java
  server/src/main/java/com/team_60/Mocco/study/repository/StudyRepository.java
  server/src/main/java/com/team_60/Mocco/study/service/StudyService.java
  server/src/main/java/com/team_60/Mocco/study/service/StudyServiceImpl.java
Labels: backend

#71 [Feature]signup page, login page 기능 및 view 구현
  client/src/atom/atom.js
  client/src/pages/LogIn.js
  client/src/pages/SignUp.js
Labels: frontend

#73 [feature] Github 연동시 사용할 Exception 및 Handler 구현
  server/build.gradle
  server/src/main/java/com/team_60/Mocco/comment/service/CommentServiceImpl.java
  server/src/main/java/com/team_60/Mocco/dto/exception/dto/ErrorMapper.java
  server/src/main/java/com/team_60/Mocco/exception/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/team_60/Mocco/exception/businessLogic/BusinessLogicException.java
  server/src/main/java/com/team_60/Mocco/exception/businessLogic/ExceptionCode.java
  server/src/main/java/com/team_60/Mocco/exception/dto/ErrorMapper.java
  server/src/main/java/com/team_60/Mocco/exception/dto/ErrorResponse.java
  server/src/main/java/com/team_60/Mocco/exception/oauth/OAuthLogicException.java
  server/src/main/java/com/team_60/Mocco/helper/password/PasswordManagerImpl.java
  server/src/main/java/com/team_60/Mocco/helper/password/PasswordManagerMock.java
  server/src/main/java/com/team_60/Mocco/member/service/MemberServiceImpl.java
  server/src/main/java/com/team_60/Mocco/proposal/service/ProposalServiceImpl.java
  server/src/main/java/com/team_60/Mocco/reply/service/ReplyServiceImpl.java
  server/src/main/java/com/team_60/Mocco/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/team_60/Mocco/security/filter/JwtTokenProvider.java
  server/src/main/java/com/team_60/Mocco/security/oauth/PrincipalDetailsService.java
  server/src/main/java/com/team_60/Mocco/security/service/SecurityService.java
  server/src/main/java/com/team_60/Mocco/study/service/StudyEvaluationServiceImpl.java
  server/src/main/java/com/team_60/Mocco/study/service/StudyProgressServiceImpl.java
  server/src/main/java/com/team_60/Mocco/study/service/StudyServiceImpl.java
  server/src/main/java/com/team_60/Mocco/study_member/serive/StudyMemberServiceImpl.java
  server/src/main/java/com/team_60/Mocco/task/service/TaskServiceImpl.java
  server/src/main/java/com/team_60/Mocco/task_check/service/TaskCheckServiceImpl.java
  server/src/main/java/com/team_60/Mocco/test/TestController.java
Labels: backend

#77 [Feature] 스터디 공고 리스트 페이지 layout 및 기능 구현
  client/.eslintrc.json
  client/src/components/PageComponent/StudyList/Component9.js
  client/src/components/PageComponent/StudyList/MakeStudyButton.js
  client/src/components/PageComponent/StudyList/SearchBar.js
  client/src/components/PageComponent/StudyList/StudyCard.js
  client/src/components/PageComponent/StudyList/StudyListTitle.js
  client/src/pages/StudyList.js
Labels: frontend

#78 [Feature] 깃허브 연동한 유저의 깃허브 로그인 기능 구현
  .gitignore
  server/build.gradle
  server/src/main/java/com/team_60/Mocco/comment/service/CommentServiceImpl.java
  server/src/main/java/com/team_60/Mocco/dto/exception/dto/ErrorMapper.java
  server/src/main/java/com/team_60/Mocco/exception/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/team_60/Mocco/exception/businessLogic/BusinessLogicException.java
  server/src/main/java/com/team_60/Mocco/exception/businessLogic/ExceptionCode.java
  server/src/main/java/com/team_60/Mocco/exception/dto/ErrorMapper.java
  server/src/main/java/com/team_60/Mocco/exception/dto/ErrorResponse.java
  server/src/main/java/com/team_60/Mocco/helper/password/PasswordManagerImpl.java
  server/src/main/java/com/team_60/Mocco/helper/password/PasswordManagerMock.java
  server/src/main/java/com/team_60/Mocco/helper/stub/StubData.java
  server/src/main/java/com/team_60/Mocco/member/entity/Member.java
  server/src/main/java/com/team_60/Mocco/member/repository/MemberRepository.java
  server/src/main/java/com/team_60/Mocco/member/service/MemberServiceImpl.java
  server/src/main/java/com/team_60/Mocco/proposal/service/ProposalServiceImpl.java
  server/src/main/java/com/team_60/Mocco/reply/service/ReplyServiceImpl.java
  server/src/main/java/com/team_60/Mocco/security/config/SecurityConfig.java
  server/src/main/java/com/team_60/Mocco/security/dto/Request.java
  server/src/main/java/com/team_60/Mocco/security/dto/Response.java
  server/src/main/java/com/team_60/Mocco/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/team_60/Mocco/security/filter/JwtTokenProvider.java
  server/src/main/java/com/team_60/Mocco/security/oauth/PrincipalDetails.java
  server/src/main/java/com/team_60/Mocco/security/oauth/PrincipalDetailsService.java
  server/src/main/java/com/team_60/Mocco/security/oauth/PrincipalOauth2UserService.java
  server/src/main/java/com/team_60/Mocco/security/service/SecurityService.java
  server/src/main/java/com/team_60/Mocco/study/dto/StudyDto.java
  server/src/main/java/com/team_60/Mocco/study/mapper/StudyMapper.java
  server/src/main/java/com/team_60/Mocco/study/service/StudyEvaluationServiceImpl.java
  server/src/main/java/com/team_60/Mocco/study/service/StudyProgressServiceImpl.java
  server/src/main/java/com/team_60/Mocco/study/service/StudyServiceImpl.java
  server/src/main/java/com/team_60/Mocco/study_member/serive/StudyMemberServiceImpl.java
  server/src/main/java/com/team_60/Mocco/task/service/TaskServiceImpl.java
  server/src/main/java/com/team_60/Mocco/task_check/service/TaskCheckServiceImpl.java
  server/src/main/java/com/team_60/Mocco/test/TestController.java
  server/src/main/resources/application-local.yml
  server/src/main/resources/application.yml
Labels: backend

#79 [Feat] Github와 Authorization Code Grant 방식으로 연동 구현
  .gitignore
  server/build.gradle
  server/src/main/java/com/team_60/Mocco/exception/businessLogic/ExceptionCode.java
  server/src/main/java/com/team_60/Mocco/helper/httpclient/GithubRestClient.java
  server/src/main/java/com/team_60/Mocco/helper/httpclient/dto/GithubRestClientDto.java
  server/src/main/java/com/team_60/Mocco/member/controller/MemberSubController.java
  server/src/main/java/com/team_60/Mocco/member/dto/MemberDto.java
  server/src/main/java/com/team_60/Mocco/member/mapper/MemberMapper.java
  server/src/main/java/com/team_60/Mocco/member/service/MemberService.java
  server/src/main/java/com/team_60/Mocco/member/service/MemberServiceImpl.java
  server/src/main/resources/application.yml
Labels: backend

#80 [Feature]Modal component 구현
  client/.eslintrc.json
  client/public/index.html
  client/src/components/Common/Modal.js
  client/src/components/Common/Potal.js
  client/src/components/PageComponent/Login/ForgotPasswordModal.js
  client/src/pages/LogIn.js
Labels: frontend

#83 [Feature]비밀번호 찾기 기능 및 view 구현
  client/.eslintrc.json
  client/src/components/Common/Modal.js
  client/src/components/PageComponent/Login/Component3.js
  client/src/components/PageComponent/Login/ForgotPasswordModal.js
  client/src/pages/LogIn.js
Labels: frontend

#85 feature : taskcheck 날짜 체크 기능 추가, login successhandler 추가
  server/src/main/java/com/team_60/Mocco/exception/businessLogic/ExceptionCode.java
  server/src/main/java/com/team_60/Mocco/security/config/SecurityConfig.java
  server/src/main/java/com/team_60/Mocco/security/filter/OAuth2SuccessHandler.java
  server/src/main/java/com/team_60/Mocco/task/repository/TaskRepository.java
  server/src/main/java/com/team_60/Mocco/task/service/TaskService.java
  server/src/main/java/com/team_60/Mocco/task/service/TaskServiceImpl.java
  server/src/main/java/com/team_60/Mocco/task_check/service/TaskCheckServiceImpl.java
Labels: backend

#86 [Feat] 진행중인 스터디 조회 API 일부 내용 추가
  server/src/main/java/com/team_60/Mocco/study/controller/StudyProgressController.java
  server/src/main/java/com/team_60/Mocco/study/dto/StudyProgressDto.java
  server/src/main/java/com/team_60/Mocco/study/mapper/StudyProgressMapper.java
  server/src/main/java/com/team_60/Mocco/task/dto/TaskDto.java
Labels: backend

#90 fix: Dev 환경에서도 비밀번호 변경, 사진 업로드 가능하게끔 수정
  server/src/main/java/com/team_60/Mocco/helper/mail/configuration/EmailConfigurationDeployEnvironment.java
  server/src/main/java/com/team_60/Mocco/helper/mail/sender/EmailSenderMock.java
  server/src/main/java/com/team_60/Mocco/helper/mail/sender/SimpleEmailSender.java
  server/src/main/java/com/team_60/Mocco/helper/password/PasswordManagerImpl.java
  server/src/main/java/com/team_60/Mocco/helper/password/PasswordManagerMock.java
  server/src/main/java/com/team_60/Mocco/helper/upload/S3ImageUploadImpl.java
  server/src/main/java/com/team_60/Mocco/helper/upload/S3ImageUploadMock.java
Labels: backend

#93 [Fix] 비밀번호 변경 API 수정 (기존 비밀번호 확인 추가)
  server/src/main/java/com/team_60/Mocco/exception/businessLogic/ExceptionCode.java
  server/src/main/java/com/team_60/Mocco/member/controller/MemberSubController.java
  server/src/main/java/com/team_60/Mocco/member/dto/MemberDto.java
  server/src/main/java/com/team_60/Mocco/member/service/MemberService.java
  server/src/main/java/com/team_60/Mocco/member/service/MemberServiceImpl.java
Labels: backend

#94 [Frontend] 회원정보 수정페이지 기능 및 view 구현
  client/src/App.js
  client/src/atom/atom.js
  client/src/components/PageComponent/ModifyUser/ChangePasswordModal.js
  client/src/components/PageComponent/ModifyUser/Component6.js
  client/src/components/PageComponent/ModifyUser/ModifyUserButton.js
  client/src/components/PageComponent/ModifyUser/ModifyUserInput.js
  client/src/components/PageComponent/ModifyUser/WithdrawalModal.js
  client/src/pages/ModifyUser.js
Labels: frontend

#96 Feature/server error fix
  server/src/main/java/com/team_60/Mocco/comment/entity/Comment.java
  server/src/main/java/com/team_60/Mocco/exception/businessLogic/ExceptionCode.java
  server/src/main/java/com/team_60/Mocco/helper/httpclient/GithubRestClient.java
  server/src/main/java/com/team_60/Mocco/helper/upload/S3ImageUploadImpl.java
  server/src/main/java/com/team_60/Mocco/study/entity/Study.java
Labels: backend

#98 Feature/ StudyListDetail, ModifyStudy 기능 및 css 구현
  client/src/components/Common/Button.js
  client/src/components/Common/ScrollTop.js
  client/src/components/PageComponent/ModifyStudy/Component111.js
  client/src/components/PageComponent/ModifyStudy/ModifyStudyItem.js
  client/src/components/PageComponent/ModifyStudy/ModifyTaskItem.js
  client/src/components/PageComponent/ModifyStudy/ModifyTaskSection.js
  client/src/components/PageComponent/StudyListDetail/ProposalTab/InputProposal.js
  client/src/components/PageComponent/StudyListDetail/ProposalTab/ProposalSection.js
  client/src/components/PageComponent/StudyListDetail/QuestionTab/CommentSection.js
  client/src/components/PageComponent/StudyListDetail/QuestionTab/InputComment.js
  client/src/components/PageComponent/StudyListDetail/QuestionTab/InputReply.js
  client/src/components/PageComponent/StudyListDetail/QuestionTab/QuestionTab.js
  client/src/components/PageComponent/StudyListDetail/QuestionTab/ReplyItem.js
  client/src/components/PageComponent/StudyListDetail/QuestionTab/ReplySection.js
  client/src/components/PageComponent/StudyListDetail/StudySection.js
  client/src/components/PageComponent/StudyListDetail/TabSection.js
  client/src/components/PageComponent/StudyListDetail/TaskItem.js
  client/src/components/PageComponent/StudyListDetail/hooks/useInputValid.js
  client/src/index.js
  client/src/pages/LogIn.js
  client/src/pages/ModifyStudy.js
  client/src/pages/StudyListDetail.js
Labels: frontend

#97 fix: study 업데이트시, Task 모두 지우고 업데이트 할 수 있게 설정함
  server/src/main/java/com/team_60/Mocco/member/service/MemberServiceImpl.java
  server/src/main/java/com/team_60/Mocco/security/config/WebConfig.java
  server/src/main/java/com/team_60/Mocco/study/service/StudyServiceImpl.java
  server/src/main/java/com/team_60/Mocco/task/service/TaskService.java
  server/src/main/java/com/team_60/Mocco/task/service/TaskServiceImpl.java
Labels: backend

#101 Feature/make study
  client/src/components/PageComponent/StudyBoard/Component8.js
  client/src/components/PageComponent/StudyBoard/Task.js
  client/src/components/PageComponent/StudyBoard/TaskContainer.js
  client/src/pages/MakeStudy.js
Labels: frontend

#102 [feat]/ mypage components
  client/.eslintrc.json
  client/package-lock.json
  client/src/App.js
  client/src/atom/atom.js
  client/src/components/PageComponent/Main/Evaluation/EvalueModal.js
  client/src/components/PageComponent/Main/Evaluation/Evalueation.js
  client/src/components/PageComponent/Main/Evaluation/Star.js
  client/src/components/PageComponent/Main/GitHubBtn/GitHubBtnBlue.js
  client/src/components/PageComponent/Main/GitHubBtn/GitHubBtnGray.js
  client/src/components/PageComponent/Main/GitHubBtn/GitHubBtnMyGray.js
  client/src/components/PageComponent/Main/GitHubGrass.js
  client/src/components/PageComponent/Main/GitHubRepo.js
  client/src/components/PageComponent/Main/MyIntro.js
  client/src/components/PageComponent/Main/MyProfile.js
  client/src/components/PageComponent/Main/MyStudyList/Carousel.js
  client/src/components/PageComponent/Main/MyStudyList/DoneList.js
  client/src/components/PageComponent/Main/MyStudyList/ProgressList.js
  client/src/components/PageComponent/Main/MyStudyList/StudyCard.js
  client/src/components/PageComponent/Main/ProfileStar.js
  client/src/components/PageComponent/Main/TotalContainer.js
  client/src/index.js
  client/src/pages/Callback.js
  client/src/pages/Main.js
Labels: frontend

#104 [fix]/mypage
  client/src/components/PageComponent/Main/Evaluation/EvalueModal.js
  client/src/components/PageComponent/Main/Evaluation/Evalueation.js
  client/src/components/PageComponent/Main/MyStudyList/Carousel.js
  client/src/components/PageComponent/Main/MyStudyList/DoneList.js
  client/src/components/PageComponent/Main/MyStudyList/ProgressList.js
  client/src/pages/Callback.js
  client/src/pages/LogIn.js
Labels: fix

#110 Fix : study board response
  server/src/main/java/com/team_60/Mocco/proposal/mapper/ProposalMapper.java
  server/src/main/java/com/team_60/Mocco/security/config/WebConfig.java
  server/src/main/java/com/team_60/Mocco/study/dto/StudyDto.java
  server/src/main/java/com/team_60/Mocco/study/mapper/StudyMapper.java
  server/src/main/java/com/team_60/Mocco/study_member/mapper/StudyMemberMapper.java
  server/src/main/java/com/team_60/Mocco/study_member/serive/StudyMemberServiceImpl.java
Labels: backend

#114 [Feature] 회원가입시, 기본 이미지 설정
  server/src/main/java/com/team_60/Mocco/member/service/MemberServiceImpl.java
Labels: backend

#116 feat: 진행중인 Study 조회 API 수정 완료
  server/src/main/java/com/team_60/Mocco/study/mapper/StudyProgressMapper.java
  server/src/main/java/com/team_60/Mocco/task/dto/TaskDto.java
Labels: backend

#118 [feature] StudyBoard 페이지 레이아웃 작업
  client/src/App.js
  client/src/components/PageComponent/MakeStudy/Component5.js
  client/src/components/PageComponent/MakeStudy/Task.js
  client/src/components/PageComponent/MakeStudy/TaskContainer.js
  client/src/components/PageComponent/StudyBoard/TaskBox/SelectUser.js
  client/src/components/PageComponent/StudyBoard/TaskBox/TaskBox.js
  client/src/components/PageComponent/StudyBoard/TaskBox/TaskList.js
  client/src/pages/MakeStudy.js
  client/src/pages/StudyBoard.js
Labels: frontend

#122 [Feature] Alarm API 구현 완료
  server/src/main/java/com/team_60/Mocco/alarm/controller/AlarmController.java
  server/src/main/java/com/team_60/Mocco/alarm/dto/AlarmDto.java
  server/src/main/java/com/team_60/Mocco/alarm/mapper/AlarmMapper.java
  server/src/main/java/com/team_60/Mocco/alarm/repository/AlarmRepository.java
  server/src/main/java/com/team_60/Mocco/alarm/service/AlarmService.java
  server/src/main/java/com/team_60/Mocco/alarm/service/AlarmServiceImpl.java
  server/src/main/java/com/team_60/Mocco/exception/businessLogic/ExceptionCode.java
  server/src/main/java/com/team_60/Mocco/helper/scheduler/Scheduler.java
  server/src/main/java/com/team_60/Mocco/helper/sse/SseService.java
  server/src/main/java/com/team_60/Mocco/proposal/service/ProposalServiceImpl.java
  server/src/main/java/com/team_60/Mocco/test/TestController.java
Labels: backend

#121 [Feat] 헤더 레이아웃 및 기본 기능 구현
  client/public/MoccoLogo.jpeg
  client/src/App.js
  client/src/components/Common/Button.js
  client/src/components/Common/Header/Header.js
  client/src/components/Common/Header/ProfileModal.js
  client/src/pages/LogIn.js
Labels: frontend

#124 [feature] aop 작업을 수동으로 controller에 넣어줌
  server/src/main/java/com/team_60/Mocco/comment/dto/CommentDto.java
  server/src/main/java/com/team_60/Mocco/dto/PostDto.java
  server/src/main/java/com/team_60/Mocco/exception/businessLogic/ExceptionCode.java
  server/src/main/java/com/team_60/Mocco/helper/aop/AuthenticationService.java
  server/src/main/java/com/team_60/Mocco/helper/aop/AuthenticationServiceDeploy.java
  server/src/main/java/com/team_60/Mocco/member/controller/MemberController.java
  server/src/main/java/com/team_60/Mocco/member/controller/MemberSubController.java
  server/src/main/java/com/team_60/Mocco/member/dto/MemberDto.java
  server/src/main/java/com/team_60/Mocco/member/service/MemberServiceImpl.java
  server/src/main/java/com/team_60/Mocco/proposal/controller/ProposalController.java
  server/src/main/java/com/team_60/Mocco/proposal/dto/ProposalDto.java
  server/src/main/java/com/team_60/Mocco/proposal/service/ProposalService.java
  server/src/main/java/com/team_60/Mocco/proposal/service/ProposalServiceImpl.java
  server/src/main/java/com/team_60/Mocco/reply/controller/ReplyController.java
  server/src/main/java/com/team_60/Mocco/reply/dto/ReplyDto.java
  server/src/main/java/com/team_60/Mocco/reply/service/ReplyService.java
  server/src/main/java/com/team_60/Mocco/reply/service/ReplyServiceImpl.java
  server/src/main/java/com/team_60/Mocco/security/cotroller/SecurityController.java
  server/src/main/java/com/team_60/Mocco/security/dto/Response.java
  server/src/main/java/com/team_60/Mocco/security/dto/SecurityDto.java
  server/src/main/java/com/team_60/Mocco/security/filter/JwtConstants.java
  server/src/main/java/com/team_60/Mocco/security/filter/JwtTokenProvider.java
  server/src/main/java/com/team_60/Mocco/security/oauth/PrincipalDetails.java
  server/src/main/java/com/team_60/Mocco/security/service/SecurityService.java
  server/src/main/java/com/team_60/Mocco/study/controller/StudyBoardController.java
  server/src/main/java/com/team_60/Mocco/study/controller/StudyEvaluationController.java
  server/src/main/java/com/team_60/Mocco/study/controller/StudyProgressController.java
  server/src/main/java/com/team_60/Mocco/study/dto/StudyEvaluationDto.java
  server/src/main/java/com/team_60/Mocco/task/controller/TaskController.java
  server/src/main/java/com/team_60/Mocco/task_check/controller/TaskCheckController.java
  server/src/main/java/com/team_60/Mocco/task_check/dto/TaskCheckDto.java
  server/src/main/java/com/team_60/Mocco/task_check/service/TaskCheckService.java
  server/src/main/java/com/team_60/Mocco/task_check/service/TaskCheckServiceImpl.java
Labels: backend

#126 [fix] aop로 구현했던 authcheck를 서비스로 바꿈
  server/src/main/java/com/team_60/Mocco/alarm/controller/AlarmController.java
  server/src/main/java/com/team_60/Mocco/alarm/entity/Alarm.java
  server/src/main/java/com/team_60/Mocco/alarm/service/AlarmService.java
  server/src/main/java/com/team_60/Mocco/alarm/service/AlarmServiceImpl.java
  server/src/main/java/com/team_60/Mocco/base_entity/BaseEntity.java
  server/src/main/java/com/team_60/Mocco/chatting/entity/Chatting.java
  server/src/main/java/com/team_60/Mocco/chatting/entity/ChattingRoom.java
  server/src/main/java/com/team_60/Mocco/comment/controller/CommentController.java
  server/src/main/java/com/team_60/Mocco/comment/entity/Comment.java
  server/src/main/java/com/team_60/Mocco/helper/aop/AuthenticationService.java
  server/src/main/java/com/team_60/Mocco/helper/aop/AuthenticationServiceDeploy.java
  server/src/main/java/com/team_60/Mocco/helper/aop/AuthenticationServiceLocal.java
  server/src/main/java/com/team_60/Mocco/member/controller/MemberController.java
  server/src/main/java/com/team_60/Mocco/member/controller/MemberSubController.java
  server/src/main/java/com/team_60/Mocco/member/entity/Member.java
  server/src/main/java/com/team_60/Mocco/member/entity/MyInfo.java
  server/src/main/java/com/team_60/Mocco/proposal/controller/ProposalController.java
  server/src/main/java/com/team_60/Mocco/proposal/entity/Proposal.java
  server/src/main/java/com/team_60/Mocco/reply/controller/ReplyController.java
  server/src/main/java/com/team_60/Mocco/reply/entity/Reply.java
  server/src/main/java/com/team_60/Mocco/security/filter/JwtTokenProvider.java
  server/src/main/java/com/team_60/Mocco/study/controller/StudyBoardController.java
  server/src/main/java/com/team_60/Mocco/study/controller/StudyEvaluationController.java
  server/src/main/java/com/team_60/Mocco/study/controller/StudyProgressController.java
  server/src/main/java/com/team_60/Mocco/study/dto/StudyDto.java
  server/src/main/java/com/team_60/Mocco/study/entity/Study.java
  server/src/main/java/com/team_60/Mocco/study/service/StudyServiceImpl.java
  server/src/main/java/com/team_60/Mocco/study_member/entity/StudyMember.java
  server/src/main/java/com/team_60/Mocco/task/entity/Task.java
  server/src/main/java/com/team_60/Mocco/task_check/controller/TaskCheckController.java
  server/src/main/java/com/team_60/Mocco/task_check/entity/TaskCheck.java
Labels: backend

#125 [Frontend] 회원정보 수정 페이지 이미지 업로드 기능 구현
  client/src/components/PageComponent/ModifyUser/ModifyUserInput.js
  client/src/pages/LogIn.js
  client/src/pages/ModifyUser.js
Labels: frontend

#128 [Feature] studyBoard 페이지 task 관련 기능 구현 및 css 작업
  client/src/App.js
  client/src/components/Common/Modal.js
  client/src/components/Common/ModalContent.js
  client/src/components/Common/ScrollTop.js
  client/src/components/PageComponent/Main/MyStudyList/ProgressList.js
  client/src/components/PageComponent/StudyBoard/AuthTask/AuthTask.js
  client/src/components/PageComponent/StudyBoard/AuthTask/AuthTaskModal.js
  client/src/components/PageComponent/StudyBoard/StudyRuleModal.js
  client/src/components/PageComponent/StudyBoard/TaskBox/SelectUser.js
  client/src/components/PageComponent/StudyBoard/TaskBox/TaskBox.js
  client/src/components/PageComponent/StudyBoard/TaskBox/TaskItem.js
  client/src/components/PageComponent/StudyBoard/TaskBox/TaskList.js
  client/src/components/PageComponent/StudyListDetail/QuestionTab/CommentSection.js
  client/src/pages/StudyBoard.js
Labels: frontend

#130 [Feat] 알람 테스트 API 구현, [Fix] 이미지 업로드 크기 및 확장자 체크
  server/src/main/java/com/team_60/Mocco/exception/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/team_60/Mocco/exception/businessLogic/ExceptionCode.java
  server/src/main/java/com/team_60/Mocco/helper/upload/S3ImageUploadImpl.java
  server/src/main/java/com/team_60/Mocco/test/TestController.java
Labels: backend, fix

#131 Feature/studyboard progress
  client/public/assets/배경.png
  client/src/App.js
  client/src/asset/달리는괴물.png
  client/src/asset/달리는사람자신파랑.png
  client/src/asset/달리는자신.png
  client/src/asset/모꼬 배경.png
  client/src/asset/배경.jpeg
  client/src/asset/좌절하는사람.png
  client/src/asset/좌절하는사람자신주황.png
  client/src/asset/좌절하는사람자신파랑.png
  client/src/components/Common/Character.js
  client/src/components/PageComponent/StudyBoard/Progress/ProgressBar.js
  client/src/components/PageComponent/StudyBoard/Progress/ProgressSection.js
  client/src/index.js
  client/src/pages/StudyBoard.js
Labels: frontend

#132 [Fix] mypage 관련 수정
  client/src/App.js
  client/src/components/PageComponent/Main/GitHubGrass.js
  client/src/components/PageComponent/Main/MyIntro.js
  client/src/components/PageComponent/StudyListDetail/StudySection.js
  client/src/pages/LogIn.js
  client/src/pages/Main.js
Labels: fix

#140 [Feature] transactional 추가
  server/src/main/java/com/team_60/Mocco/alarm/service/AlarmServiceImpl.java
  server/src/main/java/com/team_60/Mocco/comment/mapper/CommentMapper.java
  server/src/main/java/com/team_60/Mocco/comment/service/CommentServiceImpl.java
  server/src/main/java/com/team_60/Mocco/helper/password/PasswordManagerImpl.java
  server/src/main/java/com/team_60/Mocco/helper/upload/S3ImageUploadImpl.java
  server/src/main/java/com/team_60/Mocco/member/service/MemberServiceImpl.java
  server/src/main/java/com/team_60/Mocco/proposal/service/ProposalServiceImpl.java
  server/src/main/java/com/team_60/Mocco/reply/service/ReplyServiceImpl.java
  server/src/main/java/com/team_60/Mocco/study/service/StudyEvaluationServiceImpl.java
  server/src/main/java/com/team_60/Mocco/study/service/StudyProgressServiceImpl.java
  server/src/main/java/com/team_60/Mocco/study/service/StudyServiceImpl.java
  server/src/main/java/com/team_60/Mocco/study_member/serive/StudyMemberServiceImpl.java
  server/src/main/java/com/team_60/Mocco/task/service/TaskServiceImpl.java
  server/src/main/java/com/team_60/Mocco/task_check/service/TaskCheckServiceImpl.java
Labels: backend

#149 [Feature] API 입력값 Validation 구현, [Fix] SSE message 수정
  server/build.gradle
  server/src/main/java/com/team_60/Mocco/alarm/controller/AlarmController.java
  server/src/main/java/com/team_60/Mocco/alarm/service/AlarmServiceImpl.java
  server/src/main/java/com/team_60/Mocco/comment/controller/CommentController.java
  server/src/main/java/com/team_60/Mocco/comment/dto/CommentDto.java
  server/src/main/java/com/team_60/Mocco/dto/PostDto.java
  server/src/main/java/com/team_60/Mocco/exception/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/team_60/Mocco/exception/dto/ErrorResponse.java
  server/src/main/java/com/team_60/Mocco/helper/aop/AuthenticationService.java
  server/src/main/java/com/team_60/Mocco/helper/sse/SseService.java
  server/src/main/java/com/team_60/Mocco/member/controller/MemberController.java
  server/src/main/java/com/team_60/Mocco/member/controller/MemberSubController.java
  server/src/main/java/com/team_60/Mocco/member/dto/MemberDto.java
  server/src/main/java/com/team_60/Mocco/proposal/controller/ProposalController.java
  server/src/main/java/com/team_60/Mocco/proposal/dto/ProposalDto.java
  server/src/main/java/com/team_60/Mocco/reply/controller/ReplyController.java
  server/src/main/java/com/team_60/Mocco/reply/dto/ReplyDto.java
  server/src/main/java/com/team_60/Mocco/security/cotroller/SecurityController.java
  server/src/main/java/com/team_60/Mocco/security/dto/SecurityDto.java
  server/src/main/java/com/team_60/Mocco/study/controller/StudyBoardController.java
  server/src/main/java/com/team_60/Mocco/study/controller/StudyEvaluationController.java
  server/src/main/java/com/team_60/Mocco/study/controller/StudyInfoController.java
  server/src/main/java/com/team_60/Mocco/study/controller/StudyProgressController.java
  server/src/main/java/com/team_60/Mocco/study/dto/StudyDto.java
  server/src/main/java/com/team_60/Mocco/study/dto/StudyEvaluationDto.java
  server/src/main/java/com/team_60/Mocco/study/dto/StudyProgressDto.java
  server/src/main/java/com/team_60/Mocco/study/mapper/StudyProgressMapper.java
  server/src/main/java/com/team_60/Mocco/task/dto/TaskDto.java
  server/src/main/java/com/team_60/Mocco/task_check/controller/TaskCheckController.java
  server/src/main/java/com/team_60/Mocco/task_check/dto/TaskCheckDto.java
  server/src/main/java/com/team_60/Mocco/test/TestController.java
Labels: backend

#151 feature: 마이페이지 반응형 구현중. 슬라이드(4개 이하인 경우 수정필요), 자기소개 등 전체적인 반응형 레이아웃 구현
  client/src/components/PageComponent/Main/GitHubGrass.js
  client/src/components/PageComponent/Main/GitHubRepo.js
  client/src/components/PageComponent/Main/MyIntro.js
  client/src/components/PageComponent/Main/MyProfile.js
  client/src/components/PageComponent/Main/MyStudyList/Carousel.js
  client/src/components/PageComponent/Main/MyStudyList/DoneList.js
  client/src/components/PageComponent/Main/MyStudyList/ProgressList.js
  client/src/pages/Main.js
Labels: frontend

#152 [Feature] studyboard progress 애니메이션, 수치가 있는 progress bar 구현
  client/src/components/PageComponent/Main/MyProfile.js
  client/src/components/PageComponent/StudyBoard/Progress/ProgressBar.js
  client/src/components/PageComponent/StudyBoard/Progress/ProgressSection.js
  client/src/components/PageComponent/StudyBoard/TaskBox/TaskBox.js
  client/src/components/PageComponent/StudyBoard/TaskBox/UserProgressBar.js
  client/src/pages/Callback.js
  client/src/pages/StudyBoard.js
Labels: frontend

#153 [Feat] 알람 1차 구현
  client/.eslintrc.json
  client/src/components/Common/Header/Alarm.js
  client/src/components/Common/Header/Header.js
  client/src/components/Common/Header/ProfileModal.js
Labels: frontend

#154 [ Feature]studyboard 페이지 task 관련 부분 수정중
  client/src/components/Common/Modal.js
  client/src/components/PageComponent/StudyBoard/AuthTask/AuthTaskModal.js
  client/src/components/PageComponent/StudyBoard/TaskBox/SelectUser.js
  client/src/components/PageComponent/StudyBoard/TaskBox/TaskBox.js
  client/src/components/PageComponent/StudyBoard/TaskBox/TaskItem.js
  client/src/components/PageComponent/StudyListDetail/ProposalTab/ProposalSection.js
  client/src/components/PageComponent/StudyListDetail/StudySection.js
  client/src/pages/StudyBoard.js
Labels: frontend

#156 [Fix] studyboard 페이지 task 관련 부분 수정중
  client/src/components/Common/Modal.js
  client/src/components/PageComponent/StudyBoard/AuthTask/AuthTaskModal.js
  client/src/components/PageComponent/StudyBoard/TaskBox/SelectUser.js
  client/src/components/PageComponent/StudyBoard/TaskBox/TaskItem.js
  client/src/components/PageComponent/StudyListDetail/ProposalTab/ProposalSection.js
  client/src/components/PageComponent/StudyListDetail/StudySection.js
  client/src/pages/StudyBoard.js
Labels: frontend

#157 [Fix] 배포 환경 설정을 위한 코드 일부 변경
  server/src/main/java/com/team_60/Mocco/security/config/SecurityConfig.java
  server/src/main/java/com/team_60/Mocco/security/config/WebConfig.java
  server/src/main/java/com/team_60/Mocco/security/dto/SecurityDto.java
  server/src/main/java/com/team_60/Mocco/test/DeployCheckController.java
  server/src/main/resources/application-deploy.yml
Labels: backend, fix
